

# -------- query

extend type Query {
    
    # <ADMIN> role is required
    # return one appointment with specified ID
    appointment(id: ID!): AppointmentResponseType! @auth(role: ADMIN)
    
    # <ADMIN> role is required
    # search appointments by filter or specified ids ( only one way is available )
    appointments(
        ids: [ID], 
        filter: JSONObject, 
        pagination: PaginationInput, 
        sort: SortInput
    ): AppointmentResponseType! @auth(role: ADMIN)

    # <GUEST> role is required
    # returns set of busy types, that corresponds to each appointment
    # in specified range;
    busyInRange(date: DateTimeISO!, unit: TimeUnitEnum!): BusyResponseType! @auth(role: GUEST)
}


# -------- mutation

extend type Mutation {

    # <ADMIN> role is required
    # updates one appointment with specified ID
    updateAppointment(id: ID!, data: AppointmentUpdateInput): AppointmentResponseType! @auth(role: ADMIN)
    
    # <ADMIN> role is required
    # updates appointments with specified ids
    updateManyAppointments(ids: [ID]!, data: AppointmentUpdateInput): AppointmentResponseType! @auth(role: ADMIN)
    
    # <ADMIN> role is required
    # creates appointment with specified data
    createAppointment(data: AppointmentCreateInput!): AppointmentResponseType! @auth(role: GUEST)
}


# --------  types

type AppointmentType {
    id: ID!
    name: String!
    surname: String!
    address: String!
    job_desc: String!
    bwt: BestWayToTouchEnum!
    phone_number: PhoneNumber!
    date: DateTimeISO!
    duration: PositiveFloat!
    completed: Boolean!
}

type AppointmentResponseType implements APIResponseInterface {
    code: Int!
    success: Boolean!
    message: String!
    data: [AppointmentType]!
    pagination: PaginationType
}

type BusyType {
    date: DateTimeISO!
    busy: Boolean!
}

type BusyResponseType implements APIResponseInterface {
    code: Int!
    success: Boolean!
    message: String!
    data: [BusyType]!
}


# --------  inputs

input AppointmentCreateInput {
    name: String!
    surname: String!
    address: String!
    job_desc: String!
    bwt: BestWayToTouchEnum!
    phone_number: PhoneNumber!
    date: DateTimeISO!
}

input AppointmentUpdateInput {
    name: String
    surname: String
    address: String
    job_desc: String
    bwt: BestWayToTouchEnum
    phone_number: PhoneNumber
    date: DateTimeISO
    duration: PositiveFloat
    completed: Boolean
}

# --------  enums

enum BestWayToTouchEnum {
    WHATSAPP
    PHONE
    TEXT
}


enum TimeUnitEnum {
    APPOINTMENT
    DAY
}