

# -------- query

extend type Query {

    # <ADMIN> role is required
    # checks if response has "ADMIN" jwts
    checkAdmin: AuthResponseType! @auth(role: ADMIN)

    # <GUEST> role is required
    # returns current key to access admin panel
    adminPanelKey: AdminPanelKeyResponse @auth(role: GUEST)
}


# -------- mutation

extend type Mutation {
    
    # <GUEST> role is required
    # creates new auth pair with initial client crenditials
    # can be accessed from backend and from frontend
    createAT: AuthResponseType! @auth(role: GUEST)

    # <GUEST> role is required
    # gets username and password and then returns new auth tokens
    # with role "ADMIN"
    adminLogin(username: String!, password: String!): AuthResponseType @auth(role: GUEST)
    
    # <ADMIN> role is required
    # revokes admin's refresh token and gives new pair with role "GUEST"
    adminLogout: AuthResponseType! @auth(role: ADMIN)
}


# -------- types

type AuthResponseType implements APIResponseInterface {
    code: Int!
    message: String!
    success: Boolean!
    data: [ Boolean ]
}

type AdminPanelKeyResponse implements APIResponseInterface {
    code: Int!
    message: String!
    success: Boolean!
    data: [ String ]!
}

# -------- enums

enum RoleEnum {
    SUPERADMIN # can add new admins
    ADMIN # access to Admin Panel
    GUEST # like user, but not registered
    SUPERUSER # backend
    USER # simple user
}