

# -------- mutation

extend type Mutation {
    
    # <GUEST> role is required
    # creates new auth pair with initial client crenditials
    # can be accessed from backend and from frontend
    createAT: JWTResponseType! @auth(role: GUEST)

    # ONLY BACKEND CAN ACCESS
    # creates new auth pair with specified role and user_id
    createRT(user_id: ID!, role: RoleEnum!): JWTResponseType!
}


# -------- types

type JWTResponseType implements APIResponseInterface {
    code: Int!
    message: String!
    success: Boolean!
    data: [JWTType]!
}

type JWTType { 
    at: JWT! # access token
    rt: JWT! # refresh token
}

enum RoleEnum {
    SUPERADMIN # can add new admins
    ADMIN # access to Admin Panel
    GUEST # like user, but not registered
    SUPERUSER # backend
    USER # simple user
}