
# -------- query

extend type Mutation {

    # <ADMIN> role is required
    # returns upload link for new image
    startImageUpload(id: ID!): StartUploadImageResponseType! @auth(role: ADMIN)
    
    # <ADMIN> role is required
    # saves new image data to DB ( must be used only after  )
    finalizeImageUpload(id: ID!): FinalizeUploadImageResponseType! @auth(role: ADMIN)
}


# -------- types

type StartUploadImageType { 
    id: ID!
    url: URL!
}

type FinalizeUploadImageType {
    id: ID!
    url: URL!
}

type StartUploadImageResponseType implements APIResponseInterface {
    code: Int!
    message: String!
    success: Boolean!
    data: [StartUploadImageType]!
}

type FinalizeUploadImageResponseType implements APIResponseInterface {
    code: Int!
    message: String!
    success: Boolean!
    data: [FinalizeUploadImageType]!
}