
# -------- query

extend type Query {

    # <ADMIN> role is required
    # returns original config of site ( direct from DB )
    siteConfig(id: ID!): SiteConfigResponseType! @auth(role: ADMIN)
    
    # <GUEST> role is required
    # returns limited config for frontend to render some elements
    publicConfig: PublicConfigResponseType! @auth(role: GUEST)
}

extend type Mutation {

    # <ADMIN> role is required
    # updates site config
    updateSiteConfig(id: ID!, data: SiteConfigUpdateInput): SiteConfigResponseType! @auth(role: ADMIN)
}


# --------  types

type SiteConfigType {
    id: ID!
    opening_at: DateTimeISO!
    closing_at: DateTimeISO!
    min_duration: PositiveFloat!
    support_email: EmailAddress!
    phone_number: PhoneNumber!
    timezone: TimeZone!
    c_country: CountryCode!
}

type SiteConfigResponseType implements APIResponseInterface {
    code: Int!
    success: Boolean!
    message: String!
    data: [SiteConfigType]!
}

type PublicConfigType {
    opening_at: DateTimeISO!
    closing_at: DateTimeISO!
    support_email: EmailAddress!
    phone_number: PhoneNumber!
    min_duration: PositiveFloat!
    timezone: TimeZone!
    c_country: CountryCode!
}

type PublicConfigResponseType implements APIResponseInterface {
    code: Int!
    success: Boolean!
    message: String!
    data: [PublicConfigType]!
}


# --------  inputs

input SiteConfigUpdateInput {
    id: ID
    opening_at: DateTimeISO
    closing_at: DateTimeISO
    min_duration: PositiveFloat
    support_email: EmailAddress
    phone_number: PhoneNumber
    timezone: TimeZone
    c_country: CountryCode
}
