
# -------- query

extend type Query {

    # <ADMIN> role is required
    # return one work with specified ID
    work(id: ID!): WorkResponseType! @auth(role: ADMIN)

    # <ADMIN> role is required
    # search works by filter or specified ids ( only one way is available )
    works(
        ids: [ID], 
        filter: JSONObject,
        pagination: PaginationInput
        sort: SortInput    
    ): WorkResponseType! @auth(role: ADMIN)

    # <GUEST> role is required
    # as "works", but with the limited fields
    getWorks(
        filter: JSONObject!,
        pagination: PaginationInput!
        sort: SortInput
    ): PublicWorkResponseType! @auth(role: GUEST)

    # <GUEST> role is required
    # returns last images, that was uploaded by admin ( num => how many will be returned )
    newWorks(num: PositiveInt): PublicWorkResponseType! @auth(role: GUEST)
}


# -------- mutation

extend type Mutation {

    # <ADMIN> role is required
    # updates one work with specified ID
    updateWork(id: ID!, data: WorkUpdateInput): WorkResponseType! @auth(role: ADMIN)
    
    # <ADMIN> role is required
    # updates works with specified ids
    updateManyWorks(ids: [ID]!, data: WorkUpdateInput): WorkResponseType! @auth(role: ADMIN)
    
    # <ADMIN> role is required
    # deletes work with specified ID ( only from DB )
    deleteWork(id: ID!): WorkResponseType! @auth(role: ADMIN)

    # deletes works with specified IDs ( only from DB )
    deleteManyWorks(ids: [ID]!): WorkResponseType! @auth(role: ADMIN)
    
    # <ADMIN> role is required
    # creates work with specified data
    createWork(data: WorkCreateInput): WorkResponseType! @auth(role: ADMIN)
}


# -------- types

type WorkType {
    id: ID!
    img_url: URL!
    img_id: ID!
    category: WorkCategoryEnum!
    timestamp: DateTimeISO!
}

type WorkResponseType implements APIResponseInterface {
    code: Int!
    success: Boolean!
    message: String!
    data: [WorkType]!
    pagination: PaginationType
}

type PublicWorkType {
    img_url: URL!
    category: WorkCategoryEnum!
    timestamp: DateTimeISO!
}

type PublicWorkResponseType implements APIResponseInterface {
    code: Int!
    success: Boolean!
    message: String!
    data: [PublicWorkType]!
    pagination: PaginationType
}

# -------- inputs

input WorkCreateInput {
    img_id: ID!
    img_url: URL!
    category: WorkCategoryEnum!
    timestamp: DateTimeISO!
}

input WorkUpdateInput {
    img_id: ID
    img_url: URL
    category: WorkCategoryEnum
    timestamp: DateTimeISO
}


# -------- enums

enum WorkCategoryEnum {
    ASSEMBLING
    MOUNTING
    PLUMBING
}